<?php
function getQuestionsSuggestions($niveau, $theme = null)
{
    $questions = [
        'debutant' => [
            "Qu'est-ce que la cryptographie ?",
            "C’est quoi une donnée numérique ?",
            "Explique-moi les bases de la transmission de données",
            "C’est quoi un protocole réseau ?",
            "Qu’est-ce qu’une adresse IP ?",
            "Différence entre IP privée et IP publique",
            "Qu’est-ce qu’un port réseau ?",
            "C’est quoi le modèle OSI ?",
            "C’est quoi un routeur ?",
            "C’est quoi un switch ?",
            "C'est quoi la différence entre symétrique et asymétrique ?",
            "Comment fonctionne un firewall ?",
            "C'est quoi un algorithme de chiffrement ?",
            "Donne-moi un exemple simple de cryptage",
            "Quels sont les principaux protocoles de sécurité ?",
            "Comment sécuriser un réseau local ?",
            "C’est quoi un DNS ?",
            "C'est quoi HTTP et HTTPS ?",
            "C’est quoi un malware ?",
            "C’est quoi un virus informatique ?",
            "C’est quoi un cheval de Troie ?",
            "C’est quoi un ransomware ?",
            "Qu’est-ce que le phishing ?",
            "C’est quoi un mot de passe fort ?",
            "Qu’est-ce qu’une attaque informatique ?",
            "C'est quoi une clé de chiffrement ?",
            "C’est quoi une base de données ?",
            "Différence entre SQL et NoSQL",
            "C’est quoi une table en SQL ?",
            "C’est quoi un SGBD ?",
            "C’est quoi une requête SQL ?",
            "C’est quoi un algorithme ?",
            "C’est quoi une variable ?",
            "C’est quoi une boucle en programmation ?",
            "C’est quoi une condition ?",
            "C’est quoi un langage de programmation ?",
            "C’est quoi Python ?",
            "C’est quoi JavaScript ?",
            "C’est quoi un fichier HTML ?",
            "Différence entre HTML et CSS",
            "C’est quoi un serveur web ?",
            "C’est quoi une API ?",
            "C’est quoi JSON ?",
            "C’est quoi XML ?",
            "C’est quoi Linux ?",
            "Différence entre Linux et Windows",
            "C’est quoi un terminal Linux ?",
            "C’est quoi une commande shell ?",
            "C’est quoi un utilisateur root ?",
            "C’est quoi Git ?",
            "Pourquoi utilise-t-on GitHub ?",
            "C’est quoi un commit ?",
            "C’est quoi une branche Git ?",
            "C’est quoi DevOps ?",
            "C’est quoi Docker ?",
            "C’est quoi une machine virtuelle ?",
            "C’est quoi un conteneur ?",
            "C’est quoi une image Docker ?",
            "C’est quoi le cloud computing ?",
            "C’est quoi une IP statique ?",
            "C’est quoi une IP dynamique ?",
            "C’est quoi SSH ?",
            "À quoi sert une clé SSH ?",
            "C’est quoi un fichier log ?",
            "C’est quoi un pare-feu logiciel ?",
            "C'est quoi le chiffrement de bout en bout ?",
            "C’est quoi une attaque brute force ?",
            "Qu’est-ce qu’une sauvegarde de données ?",
            "Qu’est-ce qu’un script ?",
            "C’est quoi une fonction en programmation ?",
            "C’est quoi une bibliothèque logicielle ?",
            "C’est quoi un IDE ?",
            "C’est quoi une architecture client-serveur ?",
            "C’est quoi une API REST ?",
            "C’est quoi une erreur 404 ?",
            "C’est quoi une session utilisateur ?",
            "C’est quoi un cookie ?",
            "C’est quoi un certificat SSL ?",
            "C’est quoi une clé publique ?",
            "C’est quoi une clé privée ?",
            "C’est quoi un bus de données ?",
            "C’est quoi une carte mère ?",
            "C’est quoi un CPU ?",
            "C’est quoi une carte graphique ?",
            "C’est quoi la RAM ?",
            "C’est quoi la mémoire cache ?",
            "C’est quoi une machine virtuelle ?",
            "Comment fonctionne un compilateur ?",
            "C’est quoi un interpréteur ?",
            "C’est quoi un serveur DNS ?",
            "C’est quoi une adresse MAC ?",
            "C’est quoi un ping réseau ?",
            "C’est quoi un protocole UDP ?",
            "C’est quoi un protocole TCP ?",
            "C’est quoi le streaming de données ?",
            "C'est quoi un réseau local (LAN) ?",
            "C’est quoi un réseau étendu (WAN) ?",
            "C’est quoi un proxy ?",
            "C’est quoi une configuration réseau ?",
            "C’est quoi une identité numérique ?"
        ],

        'intermediaire' => [
            "Explique le fonctionnement de RSA avec un exemple",
            "Comment marche l'algorithme AES ?",
            "Qu'est-ce que la théorie des groupes en cryptographie ?",
            "Différence entre SSL et TLS ?",
            "Comment implémenter un chiffrement en Python ?",
            "C'est quoi l'arithmétique modulaire ?",
            "Explique le protocole Diffie-Hellman",
            "Comment détecter une intrusion réseau ?",
            "Comment fonctionne un VPN ?",
            "Qu’est-ce qu’une attaque DDoS ?",
            "C’est quoi un honeypot ?",
            "Comment fonctionne un IDS ?",
            "Comment fonctionne un IPS ?",
            "Qu’est-ce qu’un hash cryptographique ?",
            "Différence entre SHA-256 et MD5",
            "C’est quoi une attaque par dictionnaire ?",
            "C’est quoi une attaque par rainbow table ?",
            "C’est quoi une signature numérique ?",
            "Comment fonctionnent les certificats numériques ?",
            "Comment marche le protocole HTTPS ?",
            "Comment fonctionne le routage Internet ?",
            "C’est quoi un VLAN et comment ça marche ?",
            "Comment fonctionne l’adressage IPv6 ?",
            "Pourquoi utilise-t-on le subnetting ?",
            "C’est quoi un serveur mandataire ?",
            "C’est quoi le NAT et le PAT ?",
            "Comment fonctionne un load balancer ?",
            "Qu’est-ce que le caching DNS ?",
            "Comment optimiser une BDD SQL ?",
            "Qu’est-ce que l’indexation en SQL ?",
            "Comment fonctionnent les jointures SQL ?",
            "C’est quoi une transaction en base de données ?",
            "C’est quoi l’ACID en SQL ?",
            "C’est quoi un trigger SQL ?",
            "C’est quoi une procédure stockée ?",
            "Différence entre base de données relationnelle et non-relationnelle",
            "Comment fonctionne MongoDB ?",
            "Comment fonctionne Redis ?",
            "C’est quoi une API RESTful exactement ?",
            "C’est quoi GraphQL et comment ça fonctionne ?",
            "Comment fonctionne un serveur Node.js ?",
            "Comment fonctionne un moteur PHP ?",
            "C’est quoi une architecture MVC ?",
            "Comment fonctionne une session PHP ?",
            "Comment fonctionne un ORM ?",
            "C’est quoi une attaque XSS ?",
            "C’est quoi une attaque CSRF ?",
            "C’est quoi une injection SQL et comment l’éviter ?",
            "Comment sécuriser un site web ?",
            "C’est quoi une authentification multi-facteur (MFA) ?",
            "Comment fonctionne OAuth2 ?",
            "C’est quoi un token JWT ?",
            "Comment fonctionne Docker en interne ?",
            "Différence entre conteneur et VM",
            "Comment fonctionne Kubernetes ?",
            "C’est quoi un cluster ?",
            "C’est quoi la haute disponibilité ?",
            "Comment fonctionne un pipeline CI/CD ?",
            "Comment fonctionne Git en profondeur ?",
            "C’est quoi un merge conflict ?",
            "C’est quoi GitFlow ?",
            "Comment déployer une application web ?",
            "C’est quoi une architecture microservices ?",
            "Comment fonctionne un serveur Apache ?",
            "Comment fonctionne Nginx ?",
            "C’est quoi un reverse proxy ?",
            "Comment fonctionne SSH en détail ?",
            "Comment sécuriser un serveur Linux ?",
            "C’est quoi SELinux ?",
            "C’est quoi AppArmor ?",
            "Comment analyser des logs système ?",
            "C’est quoi un service systemd ?",
            "Comment fonctionne la mémoire virtuelle ?",
            "C’est quoi une heap et une stack ?",
            "C’est quoi un thread et un processus ?",
            "C’est quoi le parallélisme en informatique ?",
            "C’est quoi un algorithme de tri ?",
            "C’est quoi la complexité algorithmique ?",
            "C’est quoi l’analyse asymptotique ?",
            "C’est quoi une matrice et à quoi ça sert en informatique ?",
            "C’est quoi l'algèbre linéaire appliquée ?",
            "C’est quoi la dérivation en informatique ?",
            "Comment fonctionne la Fourier Transform ?",
            "C’est quoi la logique booléenne ?",
            "Comment fonctionne un automate ?",
            "C’est quoi la théorie des graphes ?",
            "Comment fonctionne un arbre binaire ?",
            "C’est quoi un heap binaire ?",
            "C’est quoi la récursivité ?",
            "Comment fonctionne un garbage collector ?",
            "C’est quoi une API SOAP ?",
            "C’est quoi le protocole MQTT ?",
            "C’est quoi WebSocket ?",
            "C’est quoi le JSON Web Encryption (JWE) ?",
            "Comment fonctionne un algorithme de compression ?",
            "C’est quoi une machine de Turing ?"
        ],

        'avance' => [
            "Démontre l'application de l'algèbre en cryptographie moderne",
            "Optimisation d'algorithmes cryptographiques",
            "Sécurité des protocoles quantiques",
            "Analyzse de vulnérabilités dans les implémentations RSA",
            "Cryptographie post-quantique : enjeux et solutions",
            "Implémentation sécurisée d'un VPN",
            "Théorie de l'information et entropie en cryptographie",
            "Attaques par canaux auxiliaires et protection",
            "Analyse complète du protocole TLS 1.3",
            "Étude de la cryptanalyse différentielle",
            "Étude de la cryptanalyse linéaire",
            "Fonctionnement mathématique des courbes elliptiques",
            "Analyse profonde de l’algorithme ECDSA",
            "Conception d’un protocole sécurisé",
            "Sécurisation d’une infrastructure critique",
            "Construction d’une PKI complète",
            "Analyse du BGP et attaques BGP hijacking",
            "Architecture d’un système distribué sécurisé",
            "Zero Trust Architecture : principes et limites",
            "Optimisation de la latence réseau à grande échelle",
            "Sécurisation d’un cluster Kubernetes",
            "Sécurisation de conteneurs Docker en production",
            "Hardening avancé d’un serveur Linux",
            "Analyse mémoire d’un malware",
            "Reverse engineering avancé",
            "Analyse forensique d’un système compromis",
            "Détection avancée d’intrusions réseau",
            "Création d’un modèle IA pour détecter des attaques",
            "Optimisation d’une base de données haute charge",
            "Conception d’une architecture microservices sécurisée",
            "Approche Zero Downtime Deployment",
            "Optimisation de pipelines CI/CD complexes",
            "Infrastructure as Code avancée (Terraform)",
            "Conception d’un système temps réel",
            "Gestion des files de messages distribuées",
            "Conception de systèmes haute disponibilité",
            "Théorie de l'information : application pratique",
            "Compression sans perte : étude mathématique",
            "Modèles mathématiques de cybersécurité",
            "Analyse de la complexité quantique",
            "Architecture cloud serverless",
            "Optimisation du stockage distribué",
            "Théorie des graphes appliquée aux réseaux",
            "Sécurisation d’une API à grande échelle",
            "Analyse profonde du fonctionnement du noyau Linux",
            "Gestion avancée de la mémoire Linux",
            "Analyse du scheduling CPU",
            "Sécurisation d’une chaîne DevOps complète",
            "Algorithmes cryptographiques résistants au Quantum",
            "Analyse brute des algorithmes NP-complets",
            "Étude de la machine virtuelle Java (JVM)",
            "Conception d’un compilateur",
            "Analyse d’algorithmes probabilistes",
            "Sécurité des communications satellites",
            "Routage avancé dans les réseaux autonomes",
            "Optimisation d’un réseau SDN",
            "Analyse de protocoles IoT",
            "Sécurisation avancée des communications mobiles",
            "Gestion de clés à grande échelle",
            "Conception d’un système distribué tolérant aux pannes",
            "Sécurité matérielle : TPM, HSM, enclaves",
            "Analyse d'une attaque side-channel complète",
            "Modélisation mathématique d’un système cryptographique"
        ]
    ]
    ;

    // Déterminer le niveau
    $niveauKey = 'debutant';
    if (strpos(strtolower($niveau), 'avancé') !== false || strpos(strtolower($niveau), '3') !== false) {
        $niveauKey = 'avance';
    } elseif (strpos(strtolower($niveau), 'intermédiaire') !== false || strpos(strtolower($niveau), '2') !== false) {
        $niveauKey = 'intermediaire';
    }

    $suggestions = $questions[$niveauKey];

    // Mélanger et retourner 3-4 questions max
    shuffle($suggestions);
    return array_slice($suggestions, 0, 4);
}

function getQuestionsParTheme($theme)
{
    $themes = [
        'cryptographie' => [
            "Explique-moi les concepts de base de la cryptographie",
            "Quelle est la différence entre chiffrement et hachage ?",
            "Donne un exemple d'algorithme symétrique",
            "Comment fonctionne la cryptographie asymétrique ?"
        ],
        'reseau' => [
            "Comment sécuriser un réseau WiFi ?",
            "Qu'est-ce qu'un VPN et comment ça marche ?",
            "Explique les protocoles TCP/IP de sécurité",
            "Comment configurer un firewall efficace ?"
        ],
        'mathematiques' => [
            "Quel est le rôle des mathématiques en cryptographie ?",
            "Explique l'arithmétique modulaire avec un exemple",
            "C'est quoi un nombre premier et pourquoi est-il important ?",
            "Comment utiliser la théorie des groupes en crypto ?"
        ]
    ];

    return $themes[$theme] ?? [];
}
?>